import type { NextPage } from "next";
import Head from "next/head";
import ConditionalSelection from "../components/RCS/ConditionalSelection";
import data from "../data";

const Home: NextPage = () => {
  return (
    <div className="flex flex-row justify-center">
      <Head>
        <title>Conditional dropdown (typescript)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full lg:w-1/3">
        <h1 className="text-4xl text-white my-6">
          Conditional dropdown (typescript)
        </h1>
        <ConditionalSelection
          exampleMode={true}
          data={data}
          showRequired={true}
          defaultValues={{
            EQUIPMENTLINE: "AMGPLUS",
            EQUIPMENTPACKAGE: "6",
            AIRBAGS: "MORE",
            ENGINEVERSIONS: "GASOLINE",
            FUELTYPE: "PETROL",
            UPHLOSTERYGROUP: "NAPPA",
            UPHLOSTERYINTERIOR: "NAP49261",
            UPHLOSTERYSEAT: "NAP49261",
          }}
        />
      </main>
    </div>
  );
};

export default Home;
